export const REQUEST_MOVIES_START = 'REQUEST_MOVIES_START';
export const REQUEST_MOVIES_ERROR = 'REQUEST_MOVIES_ERROR';
export const RECORD_MOVIES_DATA_TO_STORE = 'RECORD_MOVIES_DATA_TO_STORE';
export const RECORD_MOVIES_DATA_TO_STORE_ID = 'RECORD_MOVIES_DATA_TO_STORE_ID';
export const RECORD_MOVIE_DATA_TO_STORE = 'RECORD_MOVIE_DATA_TO_STORE';
export const REQUEST_MOVIE_ERROR = 'REQUEST_MOVIE_ERROR';
export const RESET_MOVIE_DATA_IN_STORE = 'RESET_MOVIE_DATA_IN_STORE';
